CC     := /usr/bin/gcc
CFLAGS := -lm -lfann

teste_RNA:
	$(CC) -o teste_RNA      teste_RNA.c      $(CFLAGS)

teste_RNA_with_effort:
	$(CC) -o teste_RNA_with_effort teste_RNA_with_effort.c $(CFLAGS)

clean:
	rm -f teste_RNA teste_RNA_with_effort
